name: 'Deploy Microservice'
description: 'Deploy microservice to GKE cluster'
inputs:
  microservice:
    description: 'Microservice to deploy'
    required: true
    default: ''
  config:
    description: '.env config'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Replace microservice .env content
      shell: bash
      run: |
        echo "${{ inputs.config }}" > ./apps/back/${{ inputs.microservice }}/.env

    - name: Replace prisma .env content
      uses: actions/github-script@v4
      with:
        script: |
          const fs = require('fs');
          fs.writeFileSync('./packages/prisma/.env', 'DATABASE_URL=${{ env.DATABASE_URL }}');

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_PASSWORD }}

    - name: Build and push image to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./apps/back/${{ inputs.microservice }}/Dockerfile
        push: true
        tags: "${{ env.DOCKER_HUB_USERNAME }}/repair-now-${{ inputs.microservice }}:${{ github.sha }}"