version: "3"

services:
  front:
    container_name: front
    build:
      context: .
      dockerfile: ./apps/front/Dockerfile
    restart: always
    ports:
      - 80:80
    networks:
      - app_network

  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./apps/back/api-gateway/Dockerfile
    restart: always
    ports:
      - 9000:9000
    networks:
      - app_network

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./apps/back/auth/Dockerfile
    restart: always
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
