version: "3"

services:
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5173:5173
    networks:
      - app_network
    volumes:
      - ./front:/usr/src/app/
      - /usr/src/app/node_modules

  api-gateway:
    container_name: api-gateway
    build:
      context: ./back
      dockerfile: ./apps/api-gateway/Dockerfile
    env_file:
      - ./back/apps/api-gateway/.env
    restart: always
    ports:
      - 9000:9000
    networks:
      - app_network
    volumes:
      - ./back:/usr/src/app/
      - /usr/src/app/node_modules

  auth:
    container_name: auth
    build:
      context: ./back
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - ./back/apps/auth/.env
    restart: always
    networks:
      - app_network
    volumes:
      - ./back:/usr/src/app/
      - /usr/src/app/node_modules

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
