version: "3"

services:

  postgres:
      container_name: postgres
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: repair-now
      ports:
      - 5432:5432