version: "3"

services:
  front:
    container_name: front
    build:
      context: .
      dockerfile: ./apps/front/Dockerfile
    restart: always
    ports:
      - 80:80
    networks:
      - app_network

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
