name: Deploy API Gateway

on:
  push:
    branches:
      - 'feature/docker-hub'

jobs:
  deploy-api-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Create api-gateway .env for PROD
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            fs.writeFileSync(
              './apps/back/api-gateway/.env',
              `API_GATEWAY_PORT=3000
              JWT_SECRET=${{ secrets.JWT_SECRET }}
              AUTH_HOST=auth-svc
              AUTH_PORT=3001
            `);
      
      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/back/api-gateway/Dockerfile
          push: true
          tags: "${{ secrets.DOCKER_HUB_USERNAME }}/repair-now-api-gateway:${{ github.sha }}"

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_ZONE }}

      - name: Deploy to GKE cluster
        run: |
          helm upgrade repair-now ./k8s/repair-now \
          --set GITHUB_SHA=$GITHUB_SHA \
          --set GCLOUD_PROJECT_ID=$PROJECT_ID \
          --install \