apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: repair-now-backendconfig
spec:
  timeoutSec: 1800
  connectionDraining:
    drainingTimeoutSec: 1800
---

apiVersion: v1
kind: Service
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"3005":"repair-now-backendconfig"}}'
  labels:
    app: com-gateway
  name: com-gateway-svc
spec:
  type: LoadBalancer
  selector:
    app: com-gateway
  ports:
  - name: http
    port: 3005
    targetPort: 3005