name: 'Hello World'
description: 'Greet someone'
inputs:
  config:
    description: 'Dynamic inputs'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Afficher la liste
      shell: bash
      run: |
        python3 - <<EOF
        import sys
        for line in sys.stdin:
            key, value = line.strip().split(':', 1)
            sys.stdout.write(f"Key: {key}, Value: {value}\n")
        EOF
      # run: |
      #   while read -r input; do
      #     if [[ "$input" =~ ([^:]+):(.+) ]]; then
      #       key="${BASH_REMATCH[1]}"
      #       value="${BASH_REMATCH[2]}"
      #       echo "Key: $key, Value: $value"
      #     fi
      #   done <<< "${{ inputs.config }}"
