name: 'Hello World'
description: 'Greet someone'
inputs:
  config:
    description: 'Dynamic inputs'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Afficher la liste
      shell: bash
      run: |
        IFS=$'\n'
        for input in ${{ inputs.config.split('\n') }}; do
          key=$(echo "$input" | awk -F ':' '{print $1}' | awk '{$1=$1};1')
          value=$(echo "$input" | awk -F ':' '{print $2}' | awk '{$1=$1};1')
          echo "Key: $key, Value: $value"
        done
