name: 'Hello World'
description: 'Greet someone'
inputs:
  config:
    description: 'Dynamic inputs'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Replace .env File
      shell: bash
      run: |
        echo "${{ inputs.config }}" > ./apps/back/api-gateway/.env

    - name: Show .env File
      shell: bash
      run: |
        cat ./apps/back/api-gateway/.env

    - name: Access GitHub Secret
      shell: bash
      run: |
        echo "The value of MY_SECRET is ${{ secrets.GCLOUD_PROJECT_ID }}"

    # - id: 'auth'
    #   uses: 'google-github-actions/auth@v1'
    #   with:
    #     token_format: 'access_token'
    #     credentials_json: '${{ secrets.GKE_SA_KEY }}'

    # - name: Set up GKE credentials
    #   uses: google-github-actions/get-gke-credentials@v1
    #   with:
    #     cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
    #     location: ${{ secrets.GKE_CLUSTER_ZONE }}

    # - name: Deploy microservices to GKE cluster
    #   run: |
    #     helm upgrade repair-now ./k8s/repair-now \
    #     --set GITHUB_SHA=$GITHUB_SHA \
    #     --set GCLOUD_PROJECT_ID=${{ secrets.GCLOUD_PROJECT_ID }} \
    #     --install \