name: 'Hello World'
description: 'Greet someone'
inputs:
  microservice:
    description: 'Microservice to deploy'
    required: true
    default: ''
  config:
    description: '.env config'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Replace .env File
      shell: bash
      run: |
        echo "${{ inputs.config }}" > ./apps/back/${{ inputs.microservice }}/.env

    - name: Show .env File
      shell: bash
      run: |
        cat ./apps/back/${{ inputs.microservice }}/.env

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ env.DOCKER_HUB_USERNAME }}
    #     password: ${{ env.DOCKER_HUB_PASSWORD }}

    # - name: Build and push image to Docker Hub
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     file: ./apps/back/api-gateway/Dockerfile
    #     push: true
    #     tags: "${{ env.DOCKER_HUB_USERNAME }}/repair-now-api-gateway:${{ github.sha }}"

    # - id: 'auth'
    #   uses: 'google-github-actions/auth@v1'
    #   with:
    #     token_format: 'access_token'
    #     credentials_json: $GKE_SA_KEY

    # - name: Set up GKE credentials
    #   uses: google-github-actions/get-gke-credentials@v1
    #   with:
    #     cluster_name: $GKE_CLUSTER_NAME
    #     location: $GKE_CLUSTER_ZONE

    

    # - name: Deploy microservices Gto GKE cluster
    #   shell: bash
    #   run: |
    #     helm upgrade repair-now ./k8s/repair-now \
    #     --set GITHUB_SHA=$GITHUB_SHA \
    #     --set GCLOUD_PROJECT_ID=$GCLOUD_PROJECT_ID \
    #     --install \