apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: repair-now-com-ing
  annotations:
    cloud.google.com/backend-config: "com-backendconfig"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: com-gateway-svc
                port:
                  number: 3005