apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: repair-now-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.org/websocket-services: "com-gateway-svc"
spec:
  rules:
    - http:
        paths:
          - path: /com(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: com-gateway-svc
                port:
                  number: 3005
          - path: /socket.io(/|$)(.*)
            pathType: Prefix
            backend:
              serviceName: com-gateway-svc
              servicePort: 3005
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: api-gateway-svc
                port:
                  number: 3000