apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: repair-now-ing
  annotations:
    kubernetes.io/ingress.global-static-ip-name: repair-now-ip
    networking.gke.io/managed-certificates: managed-cert
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway-svc
                port:
                  number: 3000