apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway-svc
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
  - name: tcp
    port: 3000
    targetPort: 3000