apiVersion: v1
kind: Service
metadata:
  labels:
    app: mission
  name: mission-svc
spec:
  ports:
    - name: "tcp"
      port: 3003
      protocol: TCP
      targetPort: 3003
  selector:
    app: mission
  type: ClusterIP
