name: Deploy API Gateway

on:
  push:
    branches:
      - 'feature/docker-hub'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/back/api-gateway/Dockerfile
          push: true
          tags: "${{ secrets.DOCKER_HUB_USERNAME }}/repair-now-api-gateway:${{ github.sha }}"