name: Deploy Api Gateway

on:
  push:
    branches: 
      - feature/docker-hub
      - main
  paths:
      - 'apps/back/api-gateway/**'
      - '.github/workflows/**'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./apps/back/api-gateway/Dockerfile
          push: true
          tags: $GITHUB_SHA