name: Deploy API Gateway

on:
  push:
    branches:
      - 'feature/docker-hub'

# env:
#   GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
#   GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
#   GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
#   GKE_CLUSTER_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}
#   DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
#   DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  deploy-api-gateway:
    name: Deploy Api Gateway
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
      # - name: Checkout
      #   uses: actions/checkout@v3

      # - name: Deploy Api Gateway
      #   uses: ./.github/actions/deploy-microservice
      #   with:
      #     config: |
      #       API_GATEWAY_PORT=3000
      #       JWT_SECRET=${{ secrets.JWT_SECRET }}
      #       AUTH_HOST=auth-svc
      #       AUTH_PORT=3001
