name: Deploy Back

on:
  push:
    branches:
      - 'feature/docker-hub'
    paths:
      - 'apps/back/**'
      - '.github/**'

env:
  GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_CLUSTER_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  # JOB to run change detection
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Set output
        id: set-output
        run: |
          # Récupérer les fichiers modifiés depuis la sortie de l'étape
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"

          # Liste des dossiers à vérifier
          folder_to_check=("apps/back/api-gateway" "apps/back/auth" "autre/dossier")

          # Liste des dossiers modifiés correspondants
          changed=()

          # Parcourir les fichiers modifiés
          for file in $changed_files; do
            # Parcourir la liste des dossiers à vérifier
            for folder in "${folder_to_check[@]}"; do
              # Vérifier si le fichier commence par le chemin spécifié
              if [[ $file == $folder* ]]; then
                echo "Le fichier $file commence par $folder"
                # Vérifier si le dossier n'est pas déjà présent dans la liste des dossiers modifiés
                if [[ ! " ${changed[@]} " =~ " ${folder} " ]]; then
                  # Ajouter le dossier à la liste des dossiers modifiés
                  changed+=("$folder")
                fi
                # Sortir de la boucle interne une fois qu'une correspondance est trouvée
                break
              fi
            done
          done

          echo "changed=${changed[*]" >> $GITHUB_OUTPUT

      - name: Read output
        run: |
          echo "Changed folders: ${{ steps.set-output.outputs.changed }}"

    # steps:
    #   # For pull requests it's not necessary to checkout the code
    #   - name: Checkout
    #     if: github.event_name != 'pull_request'
    #     uses: actions/checkout@v3

    #   - uses: dorny/paths-filter@v2
    #     id: filter
    #     with:
    #       filters: |
    #         api-gateway:
    #           - './apps/back/api-gateway/**'
    #         auth:
    #           - './apps/back/auth/**'

  # deploy-api-gateway:
  #   name: Deploy Api Gateway
  #   runs-on: ubuntu-latest
  #   environment: production
  #   needs: detect-changes
  #   if: ${{ needs.detect-changes.outputs.api-gateway == 'true' }}

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Deploy Api Gateway
  #       uses: ./.github/actions/deploy-microservice
  #       with:
  #         microservice: api-gateway
  #         config: |
  #           API_GATEWAY_PORT=3000
  #           JWT_SECRET=${{ secrets.JWT_SECRET }}
  #           AUTH_HOST=auth-svc
  #           AUTH_PORT=3001

  # deploy-auth:
  #   name: Deploy Auth
  #   runs-on: ubuntu-latest
  #   environment: production
  #   needs: detect-changes
  #   if: ${{ needs.detect-changes.outputs.auth == 'true' }}

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Deploy Auth
  #       uses: ./.github/actions/deploy-microservice
  #       with:
  #         microservice: auth
  #         config: |
  #           DATABASE_URL=${{ secrets.DATABASE_URL }}
  #           JWT_SECRET=${{ secrets.JWT_SECRET }}
  #           AUTH_PORT=3001