name: Deploy API Gateway

on:
  push:
    branches:
      - 'feature/docker-hub'

jobs:
  deploy-api-gateway:
    name: Deploy Api Gateway
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Utiliser l'action composite
        uses: ./.github/actions/deploy
        with:
          who-to-greet: |
            John
            Jane
            Alice

