name: Deploy Back

on:
  push:
    branches:
      - 'feature/docker-hub'
    paths:
      - 'apps/back/**'
      - '.github/**'

env:
  GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_CLUSTER_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  # JOB to run change detection
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Detect Changed Folders
        id: detect-changed-folders
        run: |
          import os

          folders = ["apps/back/api-gateway", "apps/back/auth"]

          changed = set()

          for folder in folders:
              for root, dirs, files in os.walk(folder):
                  for file in files:
                      changed.add(folder)
                      break

          unique_changed = ",".join(changed)
          print(f"Changed folders: {unique_changed}")

          # Set output
          print(f"::set-output name=test::{unique_changed}")

      - name: Read Output
        run: |
          echo "Changed folders: ${{ steps.detect-changed-folders.outputs.test }}"

    # steps:
    #   # For pull requests it's not necessary to checkout the code
    #   - name: Checkout
    #     if: github.event_name != 'pull_request'
    #     uses: actions/checkout@v3

    #   - uses: dorny/paths-filter@v2
    #     id: filter
    #     with:
    #       filters: |
    #         api-gateway:
    #           - './apps/back/api-gateway/**'
    #         auth:
    #           - './apps/back/auth/**'

  # deploy-api-gateway:
  #   name: Deploy Api Gateway
  #   runs-on: ubuntu-latest
  #   environment: production
  #   needs: detect-changes
  #   if: ${{ needs.detect-changes.outputs.api-gateway == 'true' }}

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Deploy Api Gateway
  #       uses: ./.github/actions/deploy-microservice
  #       with:
  #         microservice: api-gateway
  #         config: |
  #           API_GATEWAY_PORT=3000
  #           JWT_SECRET=${{ secrets.JWT_SECRET }}
  #           AUTH_HOST=auth-svc
  #           AUTH_PORT=3001

  # deploy-auth:
  #   name: Deploy Auth
  #   runs-on: ubuntu-latest
  #   environment: production
  #   needs: detect-changes
  #   if: ${{ needs.detect-changes.outputs.auth == 'true' }}

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Deploy Auth
  #       uses: ./.github/actions/deploy-microservice
  #       with:
  #         microservice: auth
  #         config: |
  #           DATABASE_URL=${{ secrets.DATABASE_URL }}
  #           JWT_SECRET=${{ secrets.JWT_SECRET }}
  #           AUTH_PORT=3001